[tool.roo]
name = "myproject"
version = "0.1.0"
[[tool.roo.source]]
name = "CRAN"
url = "https://cloud.r-project.org/"


[tool.roo.dependencies]
dplyr = "*"
tidyr = "*"
ggplot2 = "*"
hce = ">=0.5"
checkmate = "*"
gridExtra = "*"
tidyselect = "*"
patchwork = "*"

[tool.roo.dev-dependencies]
here = "*"
lintr = "*"
devtools = "*"
lattice = "~0.20"