# Ignored NSE variables in devtools::check
utils::globalVariables("TRTP")
utils::globalVariables("n.event")
utils::globalVariables("x")
utils::globalVariables("GROUP")
utils::globalVariables("strata")
utils::globalVariables("surv")
utils::globalVariables("proportion")
utils::globalVariables("km.y")
utils::globalVariables("km.start")
utils::globalVariables("AVAL0")
utils::globalVariables("violiny")
utils::globalVariables("violinx")
utils::globalVariables("adjusted.time")
