name: R tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ["3.6.0", "3.6.3", "4.1.0"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: actions/setup-python@v3.0.0
        with:
          python-version: "3.9"
      - name: "Install required system libraries"
        run: sudo apt-get install libcurl4-openssl-dev
      - uses: actions/cache@v2
        with:
          path: ~/.roo
          key: ${{ runner.os }}-${{ matrix.r-version}}-${{ hashFiles('**/roo.lock') }}
      - name: "Create devenv"
        run: |
          pip install roo
          roo install 
      - name: "Run unittests"
        run: |
          make unittest
